stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest
  
maven-build:
    stage: mavenbuild
    tags:
      - backend_tag
    script:
      - cd BackEnd/smartMatch
      - mvn package -B
    only:
      refs:
         - master

maven-test:
    stage: maventest
    tags:
      - backend_tag
    script:
      - cd BackEnd/smartMatch
      - mvn test
      - mvn package -B
    artifacts:
      paths:
        - Backend/exercyze/target/*.jar
    only:
      refs:
         - master

autoDeploy:
  stage: autodeploy
  tags: 
    - backend_tag
  script: 
    - cd BackEnd/smartMatch
    - mvn test
    - mvn package -B
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
        - master

android-build:
    image: javiersantos/android-ci:latest
    stage: androidbuild
    before_script:
        - export GRADLE_USER_HOME='pwd'/.gradle
        - chmod +x ./FrontEnd/gradlew
    tags:
        - androidStudio_FrontEnd
    script:
        - cd FrontEnd
        - ./gradlew assemble
    artifacts:
        paths:
            - Frontend/app/build/outputs/
    only:
      refs:
         - master

unitTests:
    image: javiersantos/android-ci:latest
    stage: androidtest
    before_script:
        - export GRADLE_USER_HOME='pwd'/.gradle
        - chmod +x ./FrontEnd/gradlew
    tags:
        - androidStudio_FrontEnd
    script:
        - cd FrontEnd
        - ./gradlew assemble
    only:
      refs:
         - master