stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest
  
maven-build:
    stage: mavenbuild
    tags:
      - shell
    script:
      - cd Backend/exercyze
      - mvn package -B

maven-test:
    stage: maventest
    tags:
      - shell
    script:
      - cd Backend/exercyze
      - mvn test
      - mvn package -B
    artifacts:
      paths:
        - Backend/exercyze/target/*.jar

autoDeploy:
  stage: autodeploy
  tags: 
    - shell
  script: 
    - cd Backend/exercyze
    - mvn test
    - mvn package -B
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

android-build:
    image: javiersantos/android-ci:latest
    stage: androidbuild
    before_script:
        - export GRADLE_USER_HOME='pwd'/.gradle
        - chmod +x ./Frontend/ExercyzeFrontend/gradlew
    tags:
        - android_tag
    script:
        - cd Frontend/ExercyzeFrontend/
        - ./gradlew assemble
    artifacts:
        paths:
            - Frontend/ExercyzeFrontend/app/build/outputs/

unitTests:
    image: javiersantos/android-ci:latest
    stage: androidtest
    before_script:
        - export GRADLE_USER_HOME='pwd'/.gradle
        - chmod +x ./Frontend/ExercyzeFrontend/gradlew
    tags:
        - android_tag
    script:
        - cd Frontend/ExercyzeFrontend/
        - ./gradlew assemble